# Generated by Django 5.2.3 on 2025-06-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_stock',
            field=models.PositiveIntegerField(),
        ),
    ]
